# Generated by Django 4.1.4 on 2023-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_details_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=dict),
            preserve_default=False,
        ),
    ]
