# Generated by Django 4.1.4 on 2023-01-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="variations",
        ),
    ]
