# Generated by Django 4.1.4 on 2023-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description_alter_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
