# Generated by Django 4.1.4 on 2023-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_variations"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, null=True, to="store.variation"),
        ),
    ]
