# Generated by Django 4.1.4 on 2023-02-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_cartitem_variation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
