# Generated by Django 4.1.4 on 2023-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_cart",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="in_wishlist",
            field=models.BooleanField(default=False),
        ),
    ]
