# Generated by Django 4.1.4 on 2023-02-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_product_in_cart_product_in_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_cart",
        ),
        migrations.RemoveField(
            model_name="product",
            name="in_wishlist",
        ),
    ]
