# Generated by Django 4.1.4 on 2023-03-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_orderitems_ordered"),
        ("store", "0012_productrating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productrating",
            name="order",
        ),
        migrations.AddField(
            model_name="productrating",
            name="order_item",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.orderitems",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
