# Generated by Django 4.1.4 on 2023-04-04 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.JSONField(blank=True, default=dict)),
                ('order_id', models.UUIDField(default=uuid.uuid1)),
                ('customer_id', models.UUIDField(default=uuid.uuid4)),
                ('cf_order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=64)),
                ('address_line_1', models.CharField(max_length=64)),
                ('address_line_2', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('pincode', models.CharField(max_length=8)),
                ('order_note', models.CharField(blank=True, max_length=128)),
                ('order_total', models.FloatField()),
                ('tax', models.FloatField(default=18)),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Conflict', 'Conflict')], default='New', max_length=16)),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ordered', models.BooleanField(default=False)),
                ('product_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
