# Generated by Django 4.1.4 on 2023-03-05 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
