# Generated by Django 4.1.4 on 2023-03-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_product_in_cart_remove_product_in_wishlist"),
        ("order", "0002_alter_order_customer_id_alter_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.cart",
            ),
        ),
    ]
