# Generated by Django 4.1.4 on 2023-04-17 11:30

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(default=order.models.get_coupon_code, max_length=20)),
                ('discount_rate', models.IntegerField()),
                ('valid_till', models.DateTimeField(blank=True, default=order.models.default_validity, null=True)),
                ('max_redeem_count', models.IntegerField(default=100)),
                ('redeemed_by', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
