# Generated by Django 4.1.4 on 2023-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_cf_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
    ]
